/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resepsionis;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import koneksi.konfigurasi;


public class daftar_pasien extends javax.swing.JInternalFrame {
    
    Connection connect = konfigurasi.Connect();
    Statement st;
    ResultSet rs;
    
    private void tampil() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Umur");
        model.addColumn("Kota");
        model.addColumn("Telepon");
        model.addColumn("Keterangan");
        
        try {
            String sql = "select * from tb_pasien";
            st = connect.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()) {
                model.addRow(new Object[] {
                    rs.getString("id_pasien"), rs.getString("nama_pasien"), rs.getString("alamat"), rs.getString("umur"), rs.getString("kota"), rs.getString("nomor_telepon"), rs.getString("keterangan")
                });
            } tbl_pasien.setModel(model);
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void bersih() {
        txt_id.setText("");
        txt_nama.setText("");
        txt_umur.setText("");
        txt_alamat.setText("");
        txt_kota.setText("");
        txt_telepon.setText("");
        txt_keterangan.setText("");
    }
    
    /**
     * Creates new form daftar_pasien
     */
    public daftar_pasien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextPane();
        txt_umur = new javax.swing.JTextField();
        txt_kota = new javax.swing.JTextField();
        txt_telepon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_keterangan = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_pasien = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1033, 391));
        setMinimumSize(new java.awt.Dimension(1033, 391));
        setPreferredSize(new java.awt.Dimension(1033, 391));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENDAFTARAN PASIEN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 11, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel5.setText("Umur");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel7.setText("Kota");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        jLabel8.setText("Nomor Telepon");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jLabel9.setText("Keterangan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jScrollPane1.setViewportView(txt_alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 220, 40));
        getContentPane().add(txt_umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 30, -1));

        txt_kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kotaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_kota, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 220, -1));
        getContentPane().add(txt_telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 220, -1));

        jScrollPane2.setViewportView(txt_keterangan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 220, 40));

        jLabel3.setText("tahun");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, 20));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, 30));

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 70, 30));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 70, 30));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 70, 30));

        tbl_pasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Alamat", "Umur", "Kota", "Telepon", "Keterangan"
            }
        ));
        tbl_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pasienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_pasien);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 670, 250));

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
        });
        getContentPane().add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 180, -1));

        jLabel6.setText("Pencarian");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, 20));
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 220, -1));

        jLabel10.setText("ID Pasien");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        txt_id.setEditable(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kotaActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "insert into tb_pasien values(NULL, '"+txt_nama.getText()+"', '"+txt_alamat.getText()+"', '"+txt_umur.getText()+"', '"+txt_kota.getText()+"', '"+txt_telepon.getText()+"', '"+txt_keterangan.getText()+"')";
            st = connect.createStatement();
            st.executeUpdate(sql);
            
            bersih();
            tampil();
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_formInternalFrameOpened

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Umur");
        model.addColumn("Kota");
        model.addColumn("Telepon");
        model.addColumn("Keterangan");
        
        try {
            String sql = "select * from tb_pasien where id_pasien like '%"+txt_cari.getText()+"%' or nama_pasien like '%"+txt_cari.getText()+"%' or umur like '%"+txt_cari.getText()+"%' or kota like '%"+txt_cari.getText()+"%' or keterangan like '%"+txt_cari.getText()+"%'";
            st = connect.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()) {
                model.addRow(new Object[] {
                    rs.getString("id_pasien"), rs.getString("nama_pasien"), rs.getString("alamat"), rs.getString("umur"), rs.getString("kota"), rs.getString("nomor_telepon"), rs.getString("keterangan")
                });
            }
            tbl_pasien.setModel(model);
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_txt_cariKeyPressed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tbl_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pasienMouseClicked
        // TODO add your handling code here:
        int baris = tbl_pasien.getSelectedRow();
        txt_id.setText(tbl_pasien.getModel().getValueAt(baris, 0).toString());
        txt_nama.setText(tbl_pasien.getModel().getValueAt(baris, 1).toString());
        txt_alamat.setText(tbl_pasien.getModel().getValueAt(baris, 2).toString());
        txt_umur.setText(tbl_pasien.getModel().getValueAt(baris, 3).toString());
        txt_kota.setText(tbl_pasien.getModel().getValueAt(baris, 4).toString());
        txt_telepon.setText(tbl_pasien.getModel().getValueAt(baris, 5).toString());
        txt_keterangan.setText(tbl_pasien.getModel().getValueAt(baris, 6).toString());
    }//GEN-LAST:event_tbl_pasienMouseClicked

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update tb_pasien set nama_pasien = '"+txt_nama.getText()+"', alamat = '"+txt_alamat.getText()+"', umur = '"+txt_umur.getText()+"', kota = '"+txt_kota.getText()+"', nomor_telepon = '"+txt_telepon.getText()+"', keterangan = '"+txt_keterangan.getText()+"' where id_pasien = '"+txt_id.getText()+"'";
            st = connect.createStatement();
            st.executeUpdate(sql);
            
            bersih();
            tampil();
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from tb_pasien where id_pasien = '"+txt_id.getText()+"'";
            st = connect.createStatement();
            st.executeUpdate(sql);
            
            bersih();
            tampil();
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_pasien;
    private javax.swing.JTextPane txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextPane txt_keterangan;
    private javax.swing.JTextField txt_kota;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_telepon;
    private javax.swing.JTextField txt_umur;
    // End of variables declaration//GEN-END:variables
}
